services:
    database:
      image: ebook-portal-database/mysql
      build:
        context: ./
        dockerfile: ./env_setup_docker/database/Dockerfile
      ports:
        - "3307:3307"
      environment:
        - MYSQL_DATABASE=ebookportal
        - MYSQL_ROOT_PASSWORD=test
      restart: always
    # liferay:
    #   image: ebook-portal/liferay
    #   buid:
    #     context: ./
    #     dockerfile: ./env_setup_docker/liferay/Dockerfile
    #   depends_on:
    #     wait-for-it:
    #       condition: service_completed_successfully
    #   ports:
    #     - "8080:8080"
    #     - "11311:11311"
    #     - "8000:8000"
    #   volumes:
    #     - ./bundles/deploy:/mnt/liferay/deploy
    #     - ./bundles/data/document_library:/opt/liferay/data/document_library
    #     - ./bundles/osgi/modules:/opt/liferay/osgi/modules
    #     - ./bundles/logs:/opt/liferay/logs
    #   environment:
    #     - LIFERAY_JPDA_ENABLED=true
    #     - LIFERAY_JVM_OPTS=-Xms4g -Xmx4g
    #     - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
    #     - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
    #     - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=10
    #     - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
    #     - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/ebookportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
    #     - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=ebookportal
    #     - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=test