/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.streaming.model.impl;

import com.streaming.model.util.CarouselItemsDashboardLocalServiceUtil;

import java.util.Date;

/**
 * The extended model base implementation for the CarouselItemsDashboard service. Represents a row in the &quot;STG-CarouselItemsDashboard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CarouselItemsDashboardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CarouselItemsDashboardImpl
 * @see CarouselItemsDashboard
 * @generated
 */
public abstract class CarouselItemsDashboardBaseImpl
	extends CarouselItemsDashboardModelImpl implements CarouselItemsDashboard {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a carousel items dashboard model instance should use the <code>CarouselItemsDashboard</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CarouselItemsDashboardLocalServiceUtil.addCarouselItemsDashboard(
				this);
		}
		else {
			CarouselItemsDashboardLocalServiceUtil.updateCarouselItemsDashboard(
				this);
		}
	}

	public abstract String getTitle();

	public abstract long getMvccVersion();

	public abstract void setMvccVersion(Long aLong);

	public abstract String getUuid();

	public abstract void setUuid(String s);

	public abstract long getPrimaryKey();

	public abstract String getExternalReferenceCode();

	public abstract void setExternalReferenceCode(String s);

	public abstract long getStreamingId();

	void setStreamingId(Long aLong);

	Object getGroupId();

	void setGroupId(Long aLong);

	Object getCompanyId();

	void setCompanyId(Long aLong);

	Object getUserId();

	void setUserId(Long aLong);

	Object getUserName();

	void setUserName(String s);

	Object getCreateDate();

	void setCreateDate(Date date);

	void setUser(String s);

	Object getUser();

	void setTitle(String s);

	void setPriority(String s);

	Object getPriority();

	void setColorTheme(String s);

	Object getColorTheme();

	Object getCategory();

	void setCategory(String s);

	void setModifiedDate(Date date);

	Object getModifiedDate();
}