/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.streaming.personal.list.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersonalList service. Represents a row in the &quot;PersonalList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.streaming.personal.list.model.impl.PersonalListModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.streaming.personal.list.model.impl.PersonalListImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersonalList
 * @generated
 */
@ProviderType
public interface PersonalListModel
	extends BaseModel<PersonalList>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a personal list model instance should use the {@link PersonalList} interface instead.
	 */

	/**
	 * Returns the primary key of this personal list.
	 *
	 * @return the primary key of this personal list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this personal list.
	 *
	 * @param primaryKey the primary key of this personal list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this personal list.
	 *
	 * @return the uuid of this personal list
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this personal list.
	 *
	 * @param uuid the uuid of this personal list
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the personal item ID of this personal list.
	 *
	 * @return the personal item ID of this personal list
	 */
	public long getPersonalItemId();

	/**
	 * Sets the personal item ID of this personal list.
	 *
	 * @param personalItemId the personal item ID of this personal list
	 */
	public void setPersonalItemId(long personalItemId);

	/**
	 * Returns the group ID of this personal list.
	 *
	 * @return the group ID of this personal list
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this personal list.
	 *
	 * @param groupId the group ID of this personal list
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this personal list.
	 *
	 * @return the company ID of this personal list
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this personal list.
	 *
	 * @param companyId the company ID of this personal list
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this personal list.
	 *
	 * @return the user ID of this personal list
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this personal list.
	 *
	 * @param userId the user ID of this personal list
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this personal list.
	 *
	 * @return the user uuid of this personal list
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this personal list.
	 *
	 * @param userUuid the user uuid of this personal list
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this personal list.
	 *
	 * @return the user name of this personal list
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this personal list.
	 *
	 * @param userName the user name of this personal list
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this personal list.
	 *
	 * @return the create date of this personal list
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this personal list.
	 *
	 * @param createDate the create date of this personal list
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this personal list.
	 *
	 * @return the modified date of this personal list
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this personal list.
	 *
	 * @param modifiedDate the modified date of this personal list
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the description of this personal list.
	 *
	 * @return the description of this personal list
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this personal list.
	 *
	 * @param description the description of this personal list
	 */
	public void setDescription(String description);

	/**
	 * Returns the file short of this personal list.
	 *
	 * @return the file short of this personal list
	 */
	@AutoEscape
	public String getFileShort();

	/**
	 * Sets the file short of this personal list.
	 *
	 * @param fileShort the file short of this personal list
	 */
	public void setFileShort(String fileShort);

	/**
	 * Returns the launch of this personal list.
	 *
	 * @return the launch of this personal list
	 */
	public boolean getLaunch();

	/**
	 * Returns <code>true</code> if this personal list is launch.
	 *
	 * @return <code>true</code> if this personal list is launch; <code>false</code> otherwise
	 */
	public boolean isLaunch();

	/**
	 * Sets whether this personal list is launch.
	 *
	 * @param launch the launch of this personal list
	 */
	public void setLaunch(boolean launch);

	/**
	 * Returns the instance pk of this personal list.
	 *
	 * @return the instance pk of this personal list
	 */
	public long getInstancePk();

	/**
	 * Sets the instance pk of this personal list.
	 *
	 * @param instancePk the instance pk of this personal list
	 */
	public void setInstancePk(long instancePk);

	/**
	 * Returns the title of this personal list.
	 *
	 * @return the title of this personal list
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this personal list.
	 *
	 * @param title the title of this personal list
	 */
	public void setTitle(String title);

	@Override
	public PersonalList cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}